.TH HELLO 1 "2026-08-13" "hello" "General Commands Manual"
.SH NAME
hello \- print a friendly greeting
.SH SYNOPSIS
.B hello
.RB [ \-h | \-\-help ]
.RB [ \-v | \-V | \-\-version ]
.SH DESCRIPTION
.B hello
is the standard Hello program. It prints "Hello, World!" to standard output.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print a usage summary and exit.
.TP
.BR \-v ", " \-V ", " \-\-version
Print the version and exit.
.SH EXIT STATUS
.TP
.B 0
Successful completion.
.SH EXAMPLES
Run the program:
.PP
.RS 4
.nf
$ hello
Hello, World!
.fi
.RE
.SH SEE ALSO
.BR hello\-rust (1)
.SH AUTHOR
Alvin Cura <alvinc@sysdudez.com>
