.TH HELLO-RUST 1 "2026-08-13" "hello" "General Commands Manual"
.SH NAME
hello-rust \- Rust implementation of the standard Hello program
.SH SYNOPSIS
.B hello-rust
.RB [ \-h | \-\-help ]
.RB [ \-v | \-V | \-\-version ]
.SH DESCRIPTION
.B hello-rust
is a zero-dependency Rust implementation of the standard Hello program. It prints "Hello, World!" to standard output.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print a usage summary and exit.
.TP
.BR \-v ", " \-V ", " \-\-version
Print the version and exit.
.SH EXIT STATUS
.TP
.B 0
Successful completion.
.SH EXAMPLES
Run the program:
.PP
.RS 4
.nf
$ hello-rust
Hello, World!
.fi
.RE
.SH SEE ALSO
.BR hello (1)
.SH AUTHOR
Alvin Cura <alvinc@sysdudez.com>
