/********************************************************************/
/* hello definitions                                             */
/* - alvinc                                                         */
/*                                                                  */
/* Hand-maintained; NOT generated by autoconf.  AC_CONFIG_HEADERS   */
/* is intentionally commented out in configure.ac, so this file is  */
/* tracked in git and edited directly.  It is shared by both the    */
/* daemon (src/skydsecd.c) and the client (src/skydsec.c).          */
/********************************************************************/

#ifndef HELLO_CONFIG_H
#define HELLO_CONFIG_H

/* Program names                                                    */
/*                                                                  */
/* One name per binary.  These were previously collapsed into a     */
/* single PROGRAM_NAME that both programs printed, so `skydsec -V`  */
/* identified itself as the daemon.                                 */
#define PROGRAM_NAME    "hello"

/* Version                                                          */
/*                                                                  */
/* Derived from AC_INIT in configure.ac, which automake passes on   */
/* the compiler command line as -DPACKAGE_VERSION.  Defining it     */
/* here independently is what allowed this file to drift to "0.5"   */
/* while the package shipped as 1.0.0.  The literal below is only a */
/* fallback for compiling outside the autotools build.              */
#ifdef PACKAGE_VERSION
#define PROGRAM_VERSION PACKAGE_VERSION
#else
#define PROGRAM_VERSION "1.0.0"
#endif


#define AUTHORS         "Alvin Cura"

#endif /* HELLO_CONFIG_H */
