/********************************************************************/
/* hello definitions                                                */
/* - alvinc                                                         */
/*                                                                  */
/* Hand-maintained; NOT generated by autoconf.  AC_CONFIG_HEADERS   */
/* is intentionally commented out in configure.ac, so this file is  */
/* tracked in git and edited directly.                              */
/********************************************************************/

#ifndef HELLO_CONFIG_H
#define HELLO_CONFIG_H

/* Program name                                                     */
#define PROGRAM_NAME    "hello"

/* Version                                                          */
/*                                                                  */
/* Derived from AC_INIT in configure.ac, which automake passes on   */
/* the compiler command line as -DPACKAGE_VERSION.                  */
#ifdef PACKAGE_VERSION
#define PROGRAM_VERSION PACKAGE_VERSION
#else
#define PROGRAM_VERSION "1.0.0"
#endif

#define AUTHORS         "Alvin Cura"

#endif /* HELLO_CONFIG_H */
